/*
 * SPDX-FileCopyrightText: Copyright Corsinvest Srl
 * SPDX-License-Identifier: AGPL-3.0-only
 */
using ClosedXML.Excel;

namespace Corsinvest.ProxmoxVE.Admin.Core.Exporters.Excel;

public class ExcelBuilder
{
    private readonly XLWorkbook _workbook;
    private readonly AppSettings _appSettings;
    private readonly List<(string SheetName, string Description)> _sheets = [];

    public ExcelBuilder(AppSettings appSettings)
    {
        _appSettings = appSettings;
        _workbook = new XLWorkbook();
        _workbook.Style.Font.FontName = "Calibri";
    }

    public ExcelBuilder AddSheet<T>(string sheetName, string description, IEnumerable<T> data, string? tableTitle = null)
    {
        var sheetBuilder = new ExcelSheetBuilder(_workbook.Worksheets.Add(sheetName));
        sheetBuilder.AddTable(tableTitle ?? sheetName, data);
        sheetBuilder.FinalizeSheet();
        _sheets.Add((sheetName, description));
        return this;
    }

    public ExcelBuilder AddSheet(string sheetName, string description, Action<ExcelSheetBuilder> configure)
    {
        var sheetBuilder = new ExcelSheetBuilder(_workbook.Worksheets.Add(sheetName));
        configure(sheetBuilder);
        sheetBuilder.FinalizeSheet();
        _sheets.Add((sheetName, description));
        return this;
    }

    public Stream Build(string title)
    {
        AddCoverPage(title);

        // Move cover to first position
        _workbook.Worksheet("Cover").Position = 1;

        var stream = new MemoryStream();
        _workbook.SaveAs(stream);
        stream.Position = 0;
        return stream;
    }

    private void AddCoverPage(string title)
    {
        var ws = _workbook.Worksheets.Add("Cover");
        var row = 1;

        // Title
        ws.Cell(row, 1).Value = title;
        ws.Cell(row, 1).Style.Font.SetBold(true);
        ws.Cell(row, 1).Style.Font.SetFontSize(20);
        ws.Range(row, 1, row, 3).Merge();
        row += 2;

        // Report info
        ws.Cell(row, 1).Value = "Report Information";
        ws.Cell(row, 1).Style.Font.SetBold(true);
        ws.Cell(row, 1).Style.Font.SetFontSize(14);
        row++;

        ws.Cell(row, 1).Value = "Generated:";
        ws.Cell(row, 2).Value = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
        row++;

        ws.Cell(row, 1).Value = "Application:";
        ws.Cell(row, 2).Value = $"{_appSettings.AppName} v{BuildInfo.Version}";
        row += 2;

        // TOC
        ws.Cell(row, 1).Value = "Contents";
        ws.Cell(row, 1).Style.Font.SetBold(true);
        ws.Cell(row, 1).Style.Font.SetFontSize(14);
        row++;

        foreach (var (sheetName, desc) in _sheets)
        {
            ws.Cell(row, 1).Value = sheetName;
            ws.Cell(row, 1).Style.Font.SetUnderline(XLFontUnderlineValues.Single);
            ws.Cell(row, 1).Style.Font.SetFontColor(XLColor.Blue);
            ws.Cell(row, 1).SetHyperlink(new XLHyperlink($"'{sheetName}'!A1"));
            ws.Cell(row, 2).Value = desc;
            row++;
        }

        row += 2;
        ws.Cell(row, 1).Value = "Generated by";
        ws.Cell(row, 1).Style.Font.SetItalic(true);
        ws.Cell(row, 1).Style.Font.SetFontColor(XLColor.Gray);
        ws.Cell(row, 2).Value = _appSettings.AppName;
        ws.Cell(row, 2).SetHyperlink(new XLHyperlink(_appSettings.AppUrl));
        ws.Cell(row, 2).Style.Font.SetFontColor(XLColor.Blue);
        ws.Cell(row, 2).Style.Font.SetUnderline(XLFontUnderlineValues.Single);
        ws.Cell(row, 2).Style.Font.SetItalic(true);

        ws.Column(1).Width = 22;
        ws.Column(2).Width = 60;
    }
}
