/*
 * SPDX-FileCopyrightText: Copyright Corsinvest Srl
 * SPDX-License-Identifier: AGPL-3.0-only
 */
using System.Text.RegularExpressions;
using ClosedXML.Excel;
using Corsinvest.ProxmoxVE.Admin.Core.Helpers;
using Corsinvest.ProxmoxVE.Admin.Core.Services;
using Corsinvest.ProxmoxVE.Admin.Module.SystemReport.Persistence;
using Corsinvest.ProxmoxVE.Api;
using Corsinvest.ProxmoxVE.Api.Extension;
using Corsinvest.ProxmoxVE.Api.Shared.Models.Cluster;
using Corsinvest.ProxmoxVE.Api.Shared.Models.Common;
using Corsinvest.ProxmoxVE.Api.Shared.Models.Node;
using Corsinvest.ProxmoxVE.Api.Shared.Models.Vm;
using Corsinvest.ProxmoxVE.Api.Shared.Utils;

namespace Corsinvest.ProxmoxVE.Admin.Module.SystemReport.Helpers;

internal class ActionHelper : BaseActionHelper<Module, Settings, DataChangedNotification>
{
    public static async Task ScanAsync(IServiceScope scope, int id)
    {
        var loggerFactory = scope.GetLoggerFactory();
        var logger = loggerFactory.CreateLogger(typeof(ActionHelper));
        var auditService = scope.GetAuditService();
        await using var db = await scope.GetDbContextAsync<ModuleDbContext>();
        var job = (await db.JobResults.FromIdAsync(id))!;
        job.Start = DateTime.UtcNow;

        using (logger.LogTimeOperation(LogLevel.Information, true, "Execute System Report for cluster '{clusterName}'", job.ClusterName))
        {
            var clusterClient = scope.GetClusterClient(job.ClusterName);
            var client = await clusterClient.GetPveClientAsync();

            var reportGenerator = new ReportGenerator(client, clusterClient, job, logger);

            var _disks = await clusterClient.CachedData.GetDisksInfoAsync(false);

            using var workbook = new XLWorkbook();
            workbook.Author = "cv4pve-admin";
            workbook.Properties.Author = "cv4pve-admin Corsinvest Srl";
            workbook.Properties.Title = "cv4pve-admin System Report";
            workbook.Properties.Subject = "cv4pve-admin System Report";
            workbook.Properties.Category = "IT Infrastructure";
            workbook.Properties.Comments = "Automated report generated by cv4pve-admin tool for Proxmox VE";
            workbook.Properties.Company = "Corsinvest Srl";

            workbook.CustomProperties.Add("Application", "cv4pve-admin");
            workbook.CustomProperties.Add("Version", Core.BuildInfo.Version);
            workbook.CustomProperties.Add("GeneratedOn", DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
            //workbook.CustomProperties.Add("ClusterName", "Production Cluster");
            //workbook.CustomProperties.Add("ExportType", "Full Report");

            await AddClusterDataAsync(workbook, client, job, _disks);
            await AddStoragesDataAsync(workbook, clusterClient, client, job);
            await AddNodesDataAsync(workbook, clusterClient, client, job, _disks);

            await AddVmsDataAsync(workbook, clusterClient, client, job, _disks, logger);

            workbook.SaveAs(job.FileName);
        }

        job.End = DateTime.UtcNow;
        job.Status = true;
        await db.SaveChangesAsync();

        await auditService.LogAsync("SystemReport.Scan", true, $"Job ID: {id}, Cluster: {job.ClusterName}");

        await PublishDataChangedAsync(scope);
    }

    private static bool HasFeature<T>(T features, T feature) where T : Enum
        => Convert.ToInt32(features) == 0 || features.HasFlag(feature);

    private static bool CheckNames(string names, string name)
    {
        if (string.IsNullOrWhiteSpace(names) || names.Equals("@all", StringComparison.OrdinalIgnoreCase)) { return true; }

        foreach (var token in names.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            if (string.IsNullOrWhiteSpace(token)) { continue; }
            if (!token.Contains('*'))
            {
                if (token.Equals(name, StringComparison.OrdinalIgnoreCase)) { return true; }
            }
            else
            {
                if (token == "*") { return true; }

                if (token.StartsWith('*') && token.Count(c => c == '*') == 1)
                {
                    if (name.EndsWith(token[1..], StringComparison.OrdinalIgnoreCase)) { return true; }
                    continue;
                }

                if (token.EndsWith('*') && token.Count(c => c == '*') == 1)
                {
                    if (name.StartsWith(token[..^1], StringComparison.OrdinalIgnoreCase)) { return true; }
                    continue;
                }

                var pattern = "^" + Regex.Escape(token).Replace(@"\*", ".*") + "$";
                if (Regex.IsMatch(name, pattern, RegexOptions.IgnoreCase)) { return true; }
            }
        }

        return false;
    }

    private static int CreateTable<T>(IXLWorksheet ws, int row, string title, IEnumerable<T> data)
    {
        ws.Cell(row, 1).Value = title;
        ws.Cell(row, 1).Style.Font.SetBold(true);
        row++;
        var table = ws.Cell(row, 1).InsertTable(data, true);
        table.AutoFilter.IsEnabled = true;
        return table.RowCount() + 2;
    }

    private static async Task AddClusterDataAsync(XLWorkbook workbook,
                                                  PveClient client,
                                                  JobResult job,
                                                  IEnumerable<VmDiskInfo> disks)
    {
        var row = 1;
        var ws = workbook.Worksheets.Add("Cluster");

        row += CreateTable(ws,
                           row,
                           "Status",
                           (await client.Cluster.Status.GetAsync())
                            .Select(a => new
                            {
                                a.Id,
                                a.Name,
                                a.Type,
                                a.Nodes,
                                a.Version,
                                a.Quorate,
                                Level = NodeHelper.DecodeLevelSupport(a.Level),
                                a.IpAddress,
                                a.NodeId,
                                a.IsOnline
                            }));

        #region Snapshots Usage
        var snapshotsUsage = new List<dynamic>();
        foreach (var forReplication in new[] { false, true })
        {
            snapshotsUsage.AddRange(disks.GroupBy(a => new { a.Type, a.Host, a.SpaceName })
                                         .Select(a => new
                                         {
                                             a.Key.Type,
                                             a.Key.Host,
                                             a.Key.SpaceName,
                                             Replication = forReplication,
                                             Count = a.SelectMany(b => b.Snapshots.Where(c => c.Replication, forReplication)).Count(),
                                             Size = a.SelectMany(b => b.Snapshots.Where(c => c.Replication, forReplication)).Sum(b => b.Size),
                                             Vms = a.Where(b => b.Snapshots.Where(c => c.Replication, forReplication).Any())
                                               .DistinctBy(a => a.VmId)
                                               .Count()
                                         }));
        }

        row += CreateTable(ws, row, "Snapshots Usage", snapshotsUsage);
        #endregion

        //security
        var users = await client.Access.Users.GetAsync(full: true);

        row += CreateTable(ws,
                           row,
                           "Users",
                           users.Select(a => new
                           {
                               a.Id,
                               Enable = a.Enable == 1,
                               a.Email,
                               Expire = DateTimeOffset.FromUnixTimeSeconds(a.Expire).DateTime
                           }));

        row += CreateTable(ws,
                           row,
                           "API Tokens",
                           users.SelectMany(a => a.Tokens).Select(a => new
                           {
                               a.Id,
                               Expire = DateTimeOffset.FromUnixTimeSeconds(a.Expire).DateTime,
                               PrivSeparated = a.Privsep == 1,
                               a.Comment
                           }));

        row += CreateTable(ws,
                           row,
                           "Groups",
                           (await client.Access.Groups.GetAsync())
                            .Select(a => new
                            {
                                a.Id,
                                a.Users,
                                a.Comment
                            }));

        row += CreateTable(ws,
                           row,
                           "Roles",
                           (await client.Access.Roles.GetAsync())
                            .Select(a => new
                            {
                                a.Id,
                                Privileges = a.Privileges.Replace(",", Environment.NewLine),
                                Special = a.Special == 1
                            }));

        row += CreateTable(ws,
                           row,
                           "Acl",
                           (await client.Access.Acl.GetAsync())
                            .Select(a => new
                            {
                                Id = a.Roleid,
                                a.Path,
                                UsersOrGroup = a.UsersGroupid,
                                Propagate = a.Propagate == 1,
                                a.Type
                            }));

        row += CreateTable(ws,
                           row,
                           "Domains",
                           (await client.Access.Domains.GetAsync())
                            .Select(a => new
                            {
                                a.Type,
                                a.Realm,
                                a.Comment
                            }));

        //backup
        row += CreateTable(ws,
                           row,
                           "Backup",
                           (await client.Cluster.Backup.GetAsync())
                            .Select(a => new
                            {
                                a.Id,
                                a.Enabled,
                                a.All,
                                VmId = a.VmId.Replace(",", Environment.NewLine),
                                a.Mode,
                                a.Storage,
                                a.StartTime,
                                a.Mailto,
                                a.Pool,
                                a.DayOfWeek,
                                a.MailNotification,
                                a.Quiet,
                                a.Compress,
                                a.Type,
                                a.Schedule,
                                a.NotesTemplate,
                                NextRun = DateTimeOffset.FromUnixTimeSeconds(a.NextRun).DateTime,
                                a.Node
                            }));

        CreateTable(ws,
                    row,
                    "Replication",
                    (await client.Cluster.Replication.GetAsync())
                        .Select(a => new
                        {
                            a.Id,
                            a.Schedule,
                            a.Type,
                            a.Guest,
                            a.JobNum,
                            a.Source,
                            a.Target,
                            a.Disable,
                            a.Rate
                        }));

        ws.Columns().AdjustToContents();
    }

    private static async Task AddStoragesDataAsync(XLWorkbook workbook, ClusterClient clusterClient, PveClient client, JobResult job)
    {
        var ws = workbook.Worksheets.Add("Storages");
        var resources = await clusterClient.CachedData.GetResourcesAsync(false);
        var items = new List<dynamic>();

        foreach (var item in resources.Where(a => a.ResourceType == ClusterResourceType.Storage)
                                      .OrderBy(a => a.Node))
        {
            if (!CheckNames(job.StorageNames, item.Storage)) { continue; }

            items.Add(new
            {
                item.Id,
                item.Node,
                item.Storage,
                item.Status,
                item.PluginType,
                Content = item.Content.Replace(",", Environment.NewLine),
                item.Shared,

                item.DiskSize,
                DiskSizeFormatted = FormatHelper.FromBytes(item.DiskSize),

                item.DiskUsage,
                DiskUsageFormatted = FormatHelper.FromBytes(item.DiskUsage),

                item.DiskUsagePercentage
            });

            await AddStorageDataAsync(workbook,
                                      clusterClient,
                                      client,
                                      item.Node,
                                      item.Storage,
                                      job.StorageFeatures,
                                      job.RrdDataTimeFrame,
                                      job.RrdDataConsolidation);
        }

        var row = 1;
        row += CreateTable(ws, row, "Storages", items);

        //link to sheet
        for (var i = 0; i < items.Count; i++)
        {
            ws.Cell(i + 3, 1).SetHyperlink(new XLHyperlink($"'{CreateSheetNameStorage(items[i].Node, items[i].Storage)}'!A1"));
        }

        ws.Columns().AdjustToContents();
    }

    private static string CreateSheetNameStorage(string node, string storage) => $"Storage {node} - {storage}";

    private static async Task AddStorageDataAsync(XLWorkbook workbook,
                                                  ClusterClient clusterClient,
                                                  PveClient client,
                                                  string node,
                                                  string storage,
                                                  StorageFeature storageFeatures,
                                                  RrdDataTimeFrame rrdDataTimeFrame,
                                                  RrdDataConsolidation rrdDataConsolidation)
    {
        var row = 1;
        var ws = workbook.Worksheets.Add(CreateSheetNameStorage(node, storage));

        if (HasFeature(storageFeatures, StorageFeature.Content))
        {
            row += CreateTable(ws,
                               row,
                               "Content",
                               (await client.Nodes[node].Storage[storage].Content.GetAsync())
                               .Select(a => new
                               {
                                   a.Content,
                                   //a.ContentDescription,
                                   a.CreationDate,
                                   a.Encrypted,
                                   a.FileName,
                                   a.Format,
                                   a.Name,
                                   a.Notes,
                                   a.Protected,
                                   a.Size,
                                   SizeFormatted = FormatHelper.FromBytes(a.Size),
                                   a.Storage,
                                   a.Verified,
                                   a.VmId
                                   //a.Volume
                               }));
        }

        if (HasFeature(storageFeatures, StorageFeature.RrdData))
        {
            CreateTable(ws,
                        row,
                        "RRD Data",
                        (await clusterClient.CachedData.GetRrdDataAsync(node, storage, rrdDataTimeFrame, rrdDataConsolidation, false))
                            .Select(a => new
                            {
                                a.TimeDate,
                                a.Used,
                                a.Size
                            }));
        }

        ws.Columns().AdjustToContents();
    }

    private static string FormatSanpshotSize(double value)
        => value == -1
            ? string.Empty
            : FormatHelper.FromBytes(value);

    private static async Task AddNodesDataAsync(XLWorkbook workbook,
                                                ClusterClient clusterClient,
                                                PveClient client,
                                                JobResult job,
                                                IEnumerable<VmDiskInfo> disks)
    {
        var ws = workbook.Worksheets.Add("Nodes");
        var resources = await clusterClient.CachedData.GetResourcesAsync(false);
        var items = new List<dynamic>();

        foreach (var item in resources.Where(a => a.ResourceType == ClusterResourceType.Node)
                                      .OrderBy(a => a.Node))
        {
            if (!CheckNames(job.NodeNames, item.Node)) { continue; }

            var status = await client.Nodes[item.Node].Status.GetAsync();
            var version = await client.Nodes[item.Node].Version.GetAsync();
            var subscription = await client.Nodes[item.Node].Subscription.GetAsync();

            var hasSnapshotsSize = HasFeature(job.NodeFeatures, NodeFeature.Services);

            var snapshotsSize = hasSnapshotsSize
                                    ? DiskInfoHelper.CalculateSnapshots(item.Node, disks, false)
                                    : 0;

            var snapshotsSizeForReplication = hasSnapshotsSize
                                                ? DiskInfoHelper.CalculateSnapshots(item.Node, disks, true)
                                                : -1;

            items.Add(new
            {
                item.Id,
                item.Node,
                item.Status,
                item.CpuSize,

                item.MemorySize,
                MemorySizeFormatted = FormatHelper.FromBytes(item.MemorySize),

                item.MemoryUsage,
                MemoryUsageFormatted = FormatHelper.FromBytes(item.MemoryUsage),
                item.MemoryUsagePercentage,

                item.DiskSize,
                DiskSizeFormatted = FormatHelper.FromBytes(item.DiskSize),
                item.DiskUsagePercentage,

                Uptime = FormatHelper.UptimeInfo(item.Uptime),

                item.CgroupMode,
                item.NodeLevel,

                CpuCpus = status.CpuInfo.Cpus,
                CpuModel = status.CpuInfo.Model,
                CpuMhz = status.CpuInfo.Mhz,
                CpuCores = status.CpuInfo.Cores,
                CpuSockets = status.CpuInfo.Sockets,

                SwapTotal = status.Swap.Total,
                SwapTotalFormatted = FormatHelper.FromBytes(status.Swap.Total),
                SwapUsed = status.Swap.Used,
                SwapUsedFormatted = FormatHelper.FromBytes(status.Swap.Used),

                status.PveVersion,

                RootFsTotal = status.RootFs.Total,
                RootFsTotalFormatted = FormatHelper.FromBytes(status.RootFs.Total),

                RootFsUsed = status.RootFs.Used,
                RootFsUsedFormatted = FormatHelper.FromBytes(status.RootFs.Used),

                KsmShared = status.Ksm.Shared,

                KernelVersion = status.Kversion,

                SubscriptionProductName = subscription.ProductName,
                SubscriptionRegDate = subscription.RegDate,

                VersionRelease = version.Release,
                VersionVersion = version.Version,

                SnapshotsSize = snapshotsSize,
                SnapshotsSizeFormatted = FormatSanpshotSize(snapshotsSize),
                SnapshotsSizeForReplication = snapshotsSizeForReplication,
                SnapshotsSizeForReplicationFormatted = FormatSanpshotSize(snapshotsSizeForReplication)
            });

            await AddNodeDataAsync(workbook,
                                   clusterClient,
                                   client,
                                   item.Node,
                                   job.NodeFeatures,
                                   job.RrdDataTimeFrame,
                                   job.RrdDataConsolidation);
        }

        var row = 1;
        row += CreateTable(ws, row, "Nodes", items);

        //link to sheet
        for (var i = 0; i < items.Count; i++)
        {
            ws.Cell(i + 3, 1).SetHyperlink(new XLHyperlink($"'{CreateSheetNameNode(items[i].Node)}'!A1"));
        }

        ws.Columns().AdjustToContents();
    }

    private static string CreateSheetNameNode(string node) => $"Node {node}";

    private static async Task AddNodeDataAsync(XLWorkbook workbook,
                                               ClusterClient clusterClient,
                                               PveClient client,
                                               string node,
                                               NodeFeature nodeFeatures,
                                               RrdDataTimeFrame rrdDataTimeFrame,
                                               RrdDataConsolidation rrdDataConsolidation)
    {
        var row = 1;
        var ws = workbook.Worksheets.Add(CreateSheetNameNode(node));

        if (HasFeature(nodeFeatures, NodeFeature.Services))
        {
            row += CreateTable(ws,
                               row,
                               "Services",
                               (await client.Nodes[node].Services.GetAsync())
                               .Select(a => new
                               {
                                   a.Name,
                                   a.State,
                                   a.IsRunning,
                                   a.Service,
                                   a.Description
                               }));
        }

        if (HasFeature(nodeFeatures, NodeFeature.Network))
        {
            row += CreateTable(ws,
                               row,
                               "Network",
                               (await client.Nodes[node].Network.GetAsync())
                               .Select(a => new
                               {
                                   a.Active,
                                   a.Type,
                                   a.Interface,
                                   a.Method,
                                   a.Method6,
                                   a.Gateway,
                                   a.Priority,
                                   a.BondMode,
                                   a.Address,
                                   a.Netmask,
                                   a.Cidr,
                                   a.Comments,
                                   Families = a.Families.JoinAsString(Environment.NewLine),
                                   a.BondMiimon,
                                   a.Slaves,
                                   AutoStart = a.AutoStart == 1,
                                   a.BondPrimary,
                                   a.BridgeStp,
                                   a.BridgeVlanAware,
                                   a.BridgeVids,
                                   a.BridgeFd,
                                   a.BridgePorts,
                                   a.Exists
                               }));
        }

        var hasDisks = HasFeature(nodeFeatures, NodeFeature.Disks);
        var hasSmartDisks = HasFeature(nodeFeatures, NodeFeature.SmartDisks);

        if (hasDisks || hasSmartDisks)
        {
            var disksData = await client.Nodes[node].Disks.List.GetAsync();
            if (hasDisks)
            {
                row += CreateTable(ws,
                                   row,
                                   "Disks",
                                   disksData.Select(a => new
                                   {
                                       a.Used,
                                       DevicePath = a.DevPath,
                                       a.Vendor,
                                       a.Serial,
                                       a.Type,
                                       a.Model,
                                       a.Wwn,
                                       a.Health,
                                       a.ByIdLink,
                                       a.Gpt,
                                       a.Wearout,
                                       a.Rpm,
                                       a.OsdId,
                                       a.Size,
                                       SizeFormatted = FormatHelper.FromBytes(a.Size)
                                   }));
            }

            if (hasSmartDisks)
            {
                var smartData = new Dictionary<string, NodeDiskSmart>();
                foreach (var item in disksData) { smartData[item.DevPath] = await client.GetDiskSmart(node, item.DevPath); }
                row += CreateTable(ws,
                                   row,
                                   "DiskSmarts",
                                   smartData.SelectMany(a => a.Value.Attributes.Select(attr => new
                                   {
                                       DevicePath = a.Key,
                                       attr.Id,
                                       attr.Name,
                                       attr.Value,
                                       attr.Worst,
                                       attr.Threshold,
                                       attr.Raw,
                                       attr.Fail,
                                       attr.Flags
                                   })));
            }
        }

        if (HasFeature(nodeFeatures, NodeFeature.Replications))
        {
            row += await AddReplicationAsync(ws, row, clusterClient, node, null);
        }

        if (HasFeature(nodeFeatures, NodeFeature.RrdData))
        {
            row += CreateTable(ws,
                               row,
                               "RRD Data",
                               (await clusterClient.CachedData.GetRrdDataAsync(node, rrdDataTimeFrame, rrdDataConsolidation, false))
                                    .Select(a => new
                                    {
                                        a.TimeDate,

                                        a.NetIn,
                                        a.NetOut,

                                        a.CpuUsagePercentage,
                                        //a.CpuSize,
                                        //a.CpuInfo,

                                        a.IoWait,

                                        a.Loadavg,

                                        a.MemorySize,
                                        a.MemoryUsage,
                                        //a.MemoryInfo,
                                        a.MemoryUsagePercentage,

                                        a.SwapSize,
                                        a.SwapUsage,

                                        a.RootSize,
                                        a.RootUsage
                                    }));
        }

        if (HasFeature(nodeFeatures, NodeFeature.AptInfo))
        {
            // apt
            row += CreateTable(ws,
                               row,
                               "Apt Update",
                               (await client.Nodes[node].Apt.Update.GetAsync())
                               .Select(a => new
                               {
                                   a.Arch,
                                   a.Origin,
                                   a.Section,
                                   a.Package,
                                   a.Priority,
                                   a.Version,
                                   a.OldVersion,
                                   a.Title,
                                   a.NotifyStatus,
                                   a.Description
                               }));

            //var repositories = await client.Nodes[node].Apt.Repositories.GetAsync();

            //row += CreateTable(ws,
            //                   row,
            //                   "Apt Standard Repositories",
            //                   repositories.SelectMany(a => a.StandardRepositories)
            //                               .Select(a => new
            //                               {
            //                                   a.Name,
            //                                   a.Description,
            //                                   a.Handle,
            //                                   a.Status,
            //                               }));

            //row += CreateTable(ws,
            //                   row,
            //                   "Apt Info",
            //                   repositories.SelectMany(a => a.Infos)
            //                               .Select(a => new
            //                               {
            //                                   a.Index,
            //                                   a.Message,
            //                                   a.Kind,
            //                                   a.Path,
            //                               }));

            //row += CreateTable(ws,
            //                   row,
            //                   "Apt Files",
            //                   repositories.SelectMany(a => a.Files)
            //                               .SelectMany(f => f.Repositories.Select(r => new
            //                               {
            //                                   Repository = r,
            //                                   f.FileType,
            //                                   f.Path
            //                               })
            //                               .Select(a => new
            //                               {
            //                                   a.Path,
            //                                   a.FileType,
            //                                   Types = a.Repository.Types.JoinAsString(","),
            //                                   Components = a.Repository.Components.JoinAsString(","),
            //                                   Suites = a.Repository.Suites.JoinAsString(","),
            //                                   a.Repository.Comment,
            //                                   a.Repository.Enabled,
            //                                   URIs = a.Repository.URIs.JoinAsString(","),
            //                               })));
        }

        if (HasFeature(nodeFeatures, NodeFeature.PackagesVersions))
        {
            row += CreateTable(ws,
                               row,
                               "Package Version",
                               (await client.Nodes[node].Apt.Versions.GetAsync())
                                   .Select(a => new
                                   {
                                       a.Arch,
                                       a.Origin,
                                       a.Section,
                                       a.Package,
                                       a.Priority,
                                       a.Version,
                                       a.OldVersion,
                                       a.Title,
                                       a.CurrentState,
                                       a.Description
                                   }));
        }

        ws.Columns().AdjustToContents();
    }

    private static async Task<int> AddReplicationAsync(IXLWorksheet ws,
                                                       int row,
                                                       ClusterClient clusterClient,
                                                       string node,
                                                       long? vmId)
        => CreateTable(ws,
                       row,
                       "Replication",
                       (await clusterClient.CachedData.GetReplicationsAsync(node, vmId, false))
                        .Select(a => new
                        {
                            a.Disable,
                            a.Id,
                            a.VmType,
                            a.Type,
                            a.Guest,
                            a.Source,
                            a.Target,
                            a.Schedule,
                            a.FailCount,
                            a.JobNum,
                            a.Duration,
                            LastSync = DateTimeOffset.FromUnixTimeSeconds(a.LastSync).DateTime,
                            NextSync = DateTimeOffset.FromUnixTimeSeconds(a.NextSync).DateTime,
                            LastTry = DateTimeOffset.FromUnixTimeSeconds(a.LastTry).DateTime,
                            a.Comment,
                            a.Error,
                            a.Rate
                        }));

    private static async Task AddVmsDataAsync(XLWorkbook workbook,
                                              ClusterClient clusterClient,
                                              PveClient client,
                                              JobResult job,
                                              IEnumerable<VmDiskInfo> disks,
                                              ILogger logger)
    {
        var ws = workbook.Worksheets.Add("Vms");
        var resources = await clusterClient.CachedData.GetResourcesAsync(false);
        var items = new List<dynamic>();

        foreach (var item in resources.Where(a => a.ResourceType == ClusterResourceType.Vm)
                                      .OrderBy(a => a.Node)
                                      .ThenBy(a => a.Type)
                                      .ThenBy(a => a.VmId))
        {
            if (!CheckNames(job.StorageNames, item.VmId.ToString())) { continue; }

            var config = await client.GetVmConfigAsync(item.Node, item.VmType, item.VmId);
            var cnfigQemu = config as VmConfigQemu;
            var configLxc = config as VmConfigLxc;

            var qemuAgentRunning = false;
            var hostname = string.Empty;
            var osInfo = string.Empty;
            var ipAddresses = string.Empty;
            VmQemuAgentNetworkGetInterfaces? qemuAgentNetworkGetInterfaces = null;

            if (item.VmType == VmType.Qemu && item.IsRunning)
            {
                var vm = client.Nodes[item.Node].Qemu[item.VmId];
                var ping = await vm.Agent.Ping.Ping();
                qemuAgentRunning = ping.IsSuccessStatusCode;

                try
                {
                    hostname = (await vm.Agent.GetHostName.GetAsync())?.Result?.HostName;
                }
                catch (Exception ex)
                {
                    logger.LogWarning(ex, "Failed to get hostname from QEMU agent for VM {VmId} on node {Node} in system report",
                        item.VmId, item.Node);
                }

                try
                {
                    osInfo = (await vm.Agent.GetOsinfo.GetAsync())?.Result?.PrettyName;
                }
                catch (Exception ex)
                {
                    logger.LogWarning(ex, "Failed to get OS info from QEMU agent for VM {VmId} on node {Node} in system report",
                        item.VmId, item.Node);
                }

                try
                {
                    qemuAgentNetworkGetInterfaces = await client.Nodes[item.Node].Qemu[item.VmId].Agent.NetworkGetInterfaces.GetAsync();
                    if (qemuAgentNetworkGetInterfaces?.Result.Any() == true)
                    {
                        ipAddresses = qemuAgentNetworkGetInterfaces.Result
                                                                   .Where(a => !string.IsNullOrEmpty(a.HardwareAddress)
                                                                                && a.HardwareAddress != "00:00:00:00:00:00"
                                                                                && a.HardwareAddress != "0:0:0:0:0:0")
                                                                   .SelectMany(a => a.IpAddresses)
                                                                   .Select(a => $"{a.IpAddress}/{a.Prefix}")
                                                                   .JoinAsString(Environment.NewLine);
                    }
                }
                catch (Exception ex)
                {
                    logger.LogWarning(ex, "Failed to get network interfaces from QEMU agent for VM {VmId} on node {Node} in system report",
                        item.VmId, item.Node);
                }
            }
            else if (item.VmType == VmType.Lxc)
            {
                hostname = configLxc!.Hostname;
                ipAddresses = configLxc.Networks
                                       .Select(a => a.IpAddress)
                                       .JoinAsString(Environment.NewLine);
            }

            var hasSnapshotsSize = HasFeature(job.VmFeatures, VmFeature.SnapshotsSize);

            var snapshotsSize = hasSnapshotsSize
                                    ? DiskInfoHelper.CalculateSnapshots(item.Node, item.VmId, disks, false)
                                    : -1;

            var snapshotsSizeForReplication = hasSnapshotsSize
                                                ? DiskInfoHelper.CalculateSnapshots(item.Node, item.VmId, disks, true)
                                                : -1;

            items.Add(new
            {
                item.Id,
                item.Node,
                item.VmId,
                item.Name,
                item.Description,
                item.Type,
                item.Status,

                item.CpuSize,
                item.CpuUsagePercentage,
                item.HostCpuUsage,

                item.MemorySize,
                MemorySizeFormatted = FormatHelper.FromBytes(item.MemorySize),

                item.MemoryUsage,
                MemoryUsageFormatted = FormatHelper.FromBytes(item.MemoryUsage),

                item.MemoryUsagePercentage,
                item.HostMemoryUsage,

                item.DiskSize,
                DiskSizeFormatted = FormatHelper.FromBytes(item.DiskSize),

                item.DiskUsage,
                DiskUsageFormatted = FormatHelper.FromBytes(item.DiskUsage),

                item.DiskUsagePercentage,

                Uptime = FormatHelper.UptimeInfo(item.Uptime),

                Hostname = hostname,
                OsInfo = osInfo,
                IpAddresses = ipAddresses,

                SnapshotsSize = snapshotsSize,
                SnapshotsSizeFormatted = FormatSanpshotSize(snapshotsSize),
                SnapshotsSizeForReplication = snapshotsSizeForReplication,
                SnapshotsSizeForReplicationFormatted = FormatSanpshotSize(snapshotsSizeForReplication),

                ConfigOnBoot = config.OnBoot,
                ConfigArch = config.Arch,
                ConfigOsType = config.OsType,
                ConfigOsTypeDecode = config.OsTypeDecode,
                ConfigProtection = config.Protection,
                ConfigVmOsType = config.VmOsType.ToString(),

                //lxc
                LxcCores = configLxc?.Cores,
                LxcNameserver = configLxc?.Nameserver,
                LxcSearchDomain = configLxc?.SearchDomain,
                LxcSwap = configLxc?.Swap,
                LxcUnprivileged = configLxc?.Unprivileged,

                //qemu
                QemuAgentRunning = qemuAgentRunning,
                QemuAcpi = cnfigQemu?.Acpi,
                QemuAgentEnabled = cnfigQemu?.AgentEnabled,
                QemuArgs = cnfigQemu?.Args,
                QemuAudio0 = cnfigQemu?.Audio0,
                QemuBalloon = (cnfigQemu?.Balloon ?? 0) == 1,
                QemuBios = cnfigQemu?.Bios,
                QemuBoot = cnfigQemu?.Boot,
                QemuBootDisk = cnfigQemu?.BootDisk,
                QemuCores = cnfigQemu?.Cores,
                QemuCpu = cnfigQemu?.Cpu,
                QemuDescription = cnfigQemu?.Description,
                QemuKeyboard = cnfigQemu?.Keyboard,
                QemuKvm = cnfigQemu?.Kvm,
                QemuLocaltime = cnfigQemu?.Localtime,
                QemuName = cnfigQemu?.Name,
                QemuNuma = cnfigQemu?.Numa,
                QemuScsiHw = cnfigQemu?.ScsiHw,
                QemuSearchDomain = cnfigQemu?.SearchDomain,
                QemuShares = cnfigQemu?.Shares,
                QemuSmbios1 = cnfigQemu?.Smbios1,
                QemuSockets = cnfigQemu?.Sockets,
                QemuStartUp = cnfigQemu?.StartUp,
                QemuTablet = cnfigQemu?.Tablet,
                QemuVga = cnfigQemu?.Vga
            });

            await AddVmDataAsync(workbook,
                                 clusterClient,
                                 client,
                                 item,
                                 config,
                                 qemuAgentNetworkGetInterfaces,
                                 job.VmFeatures,
                                 job.RrdDataTimeFrame,
                                 job.RrdDataConsolidation,
                                 disks,
                                 logger);
        }

        var row = 1;
        row += CreateTable(ws, row, "Vms", items);

        //link to sheet
        for (var i = 0; i < items.Count; i++)
        {
            ws.Cell(i + 3, 1).SetHyperlink(new XLHyperlink($"'{CreateSheetNameVm(items[i].Description)}'!A1"));
        }

        ws.Columns().AdjustToContents();
    }

    private static string CreateSheetNameVm(string description) => $"VM {description}";

    private static async Task AddVmDataAsync(XLWorkbook workbook,
                                             ClusterClient clusterClient,
                                             PveClient client,
                                             ClusterResource vm,
                                             VmConfig config,
                                             VmQemuAgentNetworkGetInterfaces? qemuAgentNetworkGetInterfaces,
                                             VmFeature vmFeatures,
                                             RrdDataTimeFrame rrdDataTimeFrame,
                                             RrdDataConsolidation rrdDataConsolidation,
                                             IEnumerable<VmDiskInfo> disks,
                                             ILogger logger)
    {
        var row = 1;
        var ws = workbook.Worksheets.Add(CreateSheetNameVm(vm.Description));

        if (HasFeature(vmFeatures, VmFeature.Network))
        {
            row += CreateTable(ws,
                               row,
                               "Network",
                               config.Networks.Select(a => new
                               {
                                   a.Name,
                                   a.Bridge,
                                   a.Type,
                                   a.Queues,
                                   a.Tag,
                                   a.Firewall,
                                   a.Gateway,
                                   a.IpAddress,
                                   a.IpAddress6,
                                   a.Gateway6,
                                   a.MacAddress,
                                   a.Model,
                                   a.Rate,
                                   a.Disconnect,
                                   a.Trunks,
                                   a.Mtu,
                                   a.LinkDown
                               }));
        }

        if (HasFeature(vmFeatures, VmFeature.Disks))
        {
            row += CreateTable(ws,
                               row,
                               "Disks",
                               config.Disks.Select(a => new
                               {
                                   a.Id,
                                   a.Storage,
                                   a.FileName,
                                   a.Device,
                                   a.Passthrough,
                                   a.MountPoint,
                                   a.MountSourcePath,
                                   a.Size,
                                   a.Backup
                               }));
        }

        if (HasFeature(vmFeatures, VmFeature.QemuGuestInfo))
        {
            //Qemu Guest Info
            if (vm.VmType == VmType.Qemu && vm.IsRunning)
            {
                try
                {
                    var fs = await client.Nodes[vm.Node].Qemu[vm.VmId].Agent.GetFsinfo.GetAsync();
                    if (fs?.Result.Any() == true)
                    {
                        row += CreateTable(ws,
                                           row,
                                           "Qemu Guest Info File Systems",
                                           fs.Result.Select(a => new
                                           {
                                               a.Name,
                                               a.MountPoint,
                                               a.Type,
                                               a.UsedBytes,
                                               a.TotalBytes,
                                               Disks = a.Disks.Select(a => $"{a.Dev} - {a.BusType} {a.Target}:{a.Bus}").JoinAsString(Environment.NewLine)
                                           }));
                    }
                }
                catch (Exception ex)
                {
                    logger.LogWarning(ex, "Failed to get filesystem info from QEMU agent for VM {VmId} on node {Node} in system report detail",
                        vm.VmId, vm.Node);
                }

                if (qemuAgentNetworkGetInterfaces?.Result.Any() == true)
                {
                    row += CreateTable(ws,
                                       row,
                                       "Qemu Guest Info Network",
                                       qemuAgentNetworkGetInterfaces.Result.Select(a => new
                                       {
                                           a.Name,
                                           a.HardwareAddress,
                                           IpAddresses = a.IpAddresses.Select(a => a.IpAddress + "/" + a.Prefix).JoinAsString(Environment.NewLine)
                                       }));
                }
            }
        }

        if (HasFeature(vmFeatures, VmFeature.RrdData))
        {
            row += CreateTable(ws,
                               row,
                              "RRD Data",
                              (await clusterClient.CachedData.GetRrdDataAsync(vm.Node,
                                                                              vm.VmType,
                                                                              vm.VmId,
                                                                              rrdDataTimeFrame,
                                                                              rrdDataConsolidation,
                                                                              false))
                                .Select(a => new
                                {
                                    a.TimeDate,

                                    a.NetIn,
                                    a.NetOut,

                                    a.CpuUsagePercentage,
                                    //a.CpuSize,
                                    //a.CpuInfo,

                                    a.MemorySize,
                                    a.MemoryUsage,
                                    //a.MemoryInfo,
                                    a.MemoryUsagePercentage,

                                    a.DiskUsage,
                                    a.DiskSize,
                                    a.DiskUsagePercentage,

                                    a.DiskRead,
                                    a.DiskWrite
                                }));
        }

        if (HasFeature(vmFeatures, VmFeature.Backup))
        {
            row += CreateTable(ws,
                               row,
                               "Backup",
                               (await client.Nodes[vm.Node].GetBackupsInAllStoragesAsync(Convert.ToInt32(vm.VmId)))
                                .Select(a => new
                                {
                                    //a.Content,
                                    a.ContentDescription,
                                    a.CreationDate,
                                    a.Encrypted,
                                    a.FileName,
                                    a.Format,
                                    a.Name,
                                    a.Notes,
                                    //a.Parent,
                                    a.Protected,
                                    a.Size,
                                    SizeFormatted = FormatHelper.FromBytes(a.Size),
                                    a.Storage,
                                    a.Verified,
                                    a.VmId
                                    //a.Volume
                                }));
        }

        if (HasFeature(vmFeatures, VmFeature.Replications))
        {
            row += await AddReplicationAsync(ws, row, clusterClient, vm.Node, vm.VmId);
        }

        if (HasFeature(vmFeatures, VmFeature.Snapshots))
        {
            row += CreateTable(ws,
                               row,
                               "Snapshots",
                               (await clusterClient.CachedData.GetSnapshotsAsync(vm.Node,
                                                                                 vm.VmType,
                                                                                 vm.VmId,
                                                                                 false))
                                .Select(a => new
                                {
                                    a.Name,
                                    a.Description,
                                    a.Parent,
                                    a.VmStatus,
                                    a.Date,
                                    Size = DiskInfoHelper.CalculateSnapshots(vm.VmId, a.Name, disks)
                                }));
        }

        ws.Columns().AdjustToContents();
    }
}
