global using System.ComponentModel.DataAnnotations;
global using Corsinvest.ProxmoxVE.Admin.Core.Extensions;
global using Corsinvest.ProxmoxVE.Admin.Core.Models;
global using Corsinvest.ProxmoxVE.Admin.Core.Modularity;
global using Corsinvest.ProxmoxVE.Admin.Core.Services;
global using Microsoft.AspNetCore.Components;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Radzen;
