name: 💬 Feedback
description: Share your feedback, suggestions, or feature requests
title: "[Feedback]: "
labels: ["feedback"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to share your feedback with us!

  - type: dropdown
    id: edition
    attributes:
      label: Edition
      description: Which edition are you using?
      options:
        - Community Edition (CE)
        - Enterprise Edition (EE)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of cv4pve-admin are you using?
      placeholder: "e.g., 2.0.0"
    validations:
      required: true

  - type: dropdown
    id: feedback-type
    attributes:
      label: Feedback Type
      description: What type of feedback is this?
      options:
        - Feature Request
        - Improvement Suggestion
        - User Experience
        - General Feedback
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your feedback in detail
      placeholder: Tell us what you think...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples that might be helpful
      placeholder: |
        - Screenshots
        - Use cases
        - Examples from other tools
