/*
 * SPDX-FileCopyrightText: Copyright Corsinvest Srl
 * SPDX-License-Identifier: AGPL-3.0-only
 */

// <auto-generated />
using System;
using Corsinvest.ProxmoxVE.Admin.Module.Diagnostic.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Corsinvest.ProxmoxVE.Admin.Module.Diagnostic.Migrations
{
    [DbContext(typeof(ModuleDbContext))]
    partial class ModuleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("diagnostic")
                .HasAnnotation("Npgsql:CollationDefinition:case_insensitive", "en-u-ks-primary,en-u-ks-primary,icu,False")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Corsinvest.ProxmoxVE.Admin.Module.Diagnostic.Models.IgnoredIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClusterName")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<int>("Context")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<int>("Gravity")
                        .HasColumnType("integer");

                    b.Property<string>("IdResource")
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<string>("SubContext")
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("ClusterName");

                    b.ToTable("IgnoredIssues", "diagnostic");
                });

            modelBuilder.Entity("Corsinvest.ProxmoxVE.Admin.Module.Diagnostic.Models.JobDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Context")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<int>("Gravity")
                        .HasColumnType("integer");

                    b.Property<string>("IdResource")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<bool>("IsIgnoredIssue")
                        .HasColumnType("boolean");

                    b.Property<int>("JobResultId")
                        .HasColumnType("integer");

                    b.Property<string>("SubContext")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("JobResultId");

                    b.ToTable("JobDetails", "diagnostic");
                });

            modelBuilder.Entity("Corsinvest.ProxmoxVE.Admin.Module.Diagnostic.Models.JobResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClusterName")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<int>("Critical")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Info")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Warning")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClusterName");

                    b.ToTable("JobResults", "diagnostic");
                });

            modelBuilder.Entity("Corsinvest.ProxmoxVE.Admin.Module.Diagnostic.Models.JobDetail", b =>
                {
                    b.HasOne("Corsinvest.ProxmoxVE.Admin.Module.Diagnostic.Models.JobResult", "JobResult")
                        .WithMany("Details")
                        .HasForeignKey("JobResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobResult");
                });

            modelBuilder.Entity("Corsinvest.ProxmoxVE.Admin.Module.Diagnostic.Models.JobResult", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
