// <auto-generated />
using System;
using Corsinvest.ProxmoxVE.Admin.Module.BackupAnalytics.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Corsinvest.ProxmoxVE.Admin.Module.BackupAnalytics.Migrations
{
    [DbContext(typeof(ModuleDbContext))]
    [Migration("20250616133428_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("backup_insights")
                .HasAnnotation("Npgsql:CollationDefinition:case_insensitive", "en-u-ks-primary,en-u-ks-primary,icu,False")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Corsinvest.ProxmoxVE.Admin.Module.BackupAnalytics.Models.JobResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Archive")
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<string>("Logs")
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<double>("Size")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("TaskResultId")
                        .HasColumnType("integer");

                    b.Property<double>("TransferSize")
                        .HasColumnType("double precision");

                    b.Property<string>("VmId")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("End");

                    b.HasIndex("Start");

                    b.HasIndex("TaskResultId");

                    b.HasIndex("VmId");

                    b.ToTable("JobResults", "backup_insights");
                });

            modelBuilder.Entity("Corsinvest.ProxmoxVE.Admin.Module.BackupAnalytics.Models.TaskResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClusterName")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Logs")
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<string>("Node")
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<string>("Storage")
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<string>("TaskId")
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("ClusterName");

                    b.HasIndex("End");

                    b.HasIndex("Start");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskResults", "backup_insights");
                });

            modelBuilder.Entity("Corsinvest.ProxmoxVE.Admin.Module.BackupAnalytics.Models.JobResult", b =>
                {
                    b.HasOne("Corsinvest.ProxmoxVE.Admin.Module.BackupAnalytics.Models.TaskResult", "TaskResult")
                        .WithMany("Jobs")
                        .HasForeignKey("TaskResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskResult");
                });

            modelBuilder.Entity("Corsinvest.ProxmoxVE.Admin.Module.BackupAnalytics.Models.TaskResult", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
